name: Codebreaker test and deploy

on:
  workflow_dispatch:

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
    id-token: write
    contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: Codebreaker-Backend
      solution-path: src/Chapter08.sln

  build-and-deploy:
    needs: build-and-test
    uses: ./.github/workflows/shared-deploy.yml
    with:
       environment-name: ${{ vars.AZURE_ENV_NAME }}
       location: ${{ vars.AZURE_LOCATION }}
    secrets:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}