name: Codebreaker production

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: Codebreaker-Backend
      solution-path: src/Chapter08.sln

  build-and-deploy:
    needs: build-and-test
    uses: ./.github/workflows/shared-deploy-withenvironment.yml
    secrets: inherit
    with:
      environment-name: codebreaker-08-prod